export const sagaActions = {
    TWO_FACTOR_AUTH: 'TWO_FACTOR_AUTH',
    TWO_FACTOR_VERIFY: 'TWO_FACTOR_VERIFY',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    GET_USERS: 'GET_USERS',
    DELETE_USER: 'DELETE_USER',
    ADD_USER: 'ADD_USER',
    EDIT_USER: 'EDIT_USER',
    SEND_MESSAGE_TO_USERS: 'SEND_MESSAGE_TO_USERS',
  }
  